#!/usr/bin/python
#coding:utf-8

import subprocess
import tempfile
import settings

local_image = tempfile.mktemp()
nullw = open('/dev/null', 'w')
nullr = open('/dev/null')
cmd = ['screencapture', '-ix', local_image]
p = subprocess.Popen(cmd, stdout=nullw, stdin=nullr, stderr=nullw)

import localfile
import os

conf = settings.get_conf()
p.wait()

def setClipboard(data):                     
    from AppKit import NSPasteboard, NSArray
    pb = NSPasteboard.generalPasteboard()
    pb.clearContents()
    a = NSArray.arrayWithObject_(data)
    pb.writeObjects_(a)

assert os.path.exists(local_image)
filename = localfile.mkfilename(conf['file']) # Build filename

if conf['upload']['upload']:
	if conf['upload']['to'].lower() == "imgur":
		import imgur
		setClipboard(imgur.upload(local_image, conf['upload']['imgur']['api-key']))

	elif conf['upload']['to'].lower() == "scp":
		import scp
		setClipboard(scp.upload(local_image, filename, conf['upload']['scp']))

	elif conf['upload']['to'].lower() == "dropbox":
		import dropbox_upload
		setClipboard(dropbox_upload.upload(local_image, filename, conf['upload']['dropbox']))

if conf['file']['keep']:
	localfile.move(local_image, conf['file']['dir'], filename)
else:
	os.unlink(local_image)
subprocess.Popen(["afplay","/System/Library/Sounds/Glass.aiff"])
